/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "STM32_F103C6.h"
#include "STM32F103C6_GPIO_DRIVERS.h"
#include "STM32F103C6_RCC_DRIVERS.h"
#include "STM32F103C6_I2C_DRIVER.h"
#include "I2C_SLAVE_EEPROM.h"




int main(void)
{
	//Enable clock


	//Test case 1
	unsigned char ch1[] = {0x1,0x2,0x3,0x4,0x5,0x6,0x7};
	unsigned char ch2[7] = {0};

	EEPROM_Init();
	EEPROM_Write_NBytes(0xAF, ch1, 7);
	EEPROM_Read_Byte(0xAF, ch2, 7);

	///Test Case
	ch1[0] = 0xA ;
	ch1[1] = 0xB ;
	ch1[2] = 0xC ;
	ch1[3] = 0xD ;
	EEPROM_Write_NBytes(0xFFF, ch1, 4);
	EEPROM_Read_Byte(0xFFF, ch2, 4);




	while(1)
	{


	}

	return 0;

}

