/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST  under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include<stdint.h>
#define SYSCTL_RCGC2_R   (*((volatile unsigned long*)0x400FE108))//control register enable GOIP
#define GPIO_PORTF_DIR_R ((*(volatile unsigned long*)0x040025400))//to determine direction
#define GPIO_PORTF_DEN_R ((*(volatile unsigned long*)0x04002551C)) //enable pin 
#define GPIO_PORTF_DATA_R ((*(volatile unsigned long*)0x0400253FC)) //write on pin

int main(void)
{   
	volatile unsigned long delay_count;
    SYSCTL_RCGC2_R=0x20;
    //delay to make sure GPOIF is up running 
    for(delay_count=0;delay_count<200;delay_count++);
    	/*in this if optmization was opened it will delet it so 
    	delay_count sholud be volatile*/

    GPIO_PORTF_DIR_R|=1<<3; //to make F3 is output
    GPIO_PORTF_DEN_R|=1<<3; //to enable f3

    while(1)
    {
    	GPIO_PORTF_DATA_R|=1<<3;
    	for(delay_count=0;delay_count<200000;delay_count++);
        GPIO_PORTF_DATA_R&=~(1<<3);
        for(delay_count=0;delay_count<200000;delay_count++);
    }

	return 0;
} 