/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdlib.h>
#include <stdint.h>
#include <stdio.h>

//GPIOs Base Addresses

#define GPIOA_Base             0x40010800
#define GPIOB_Base             0x40010C00
#define RCC_Base               0x40021000

//GPIOA Registers
#define GPIOA_CRL            *(volatile uint32_t * )(GPIOA_Base + 0x00)
#define GPIOA_CRH            *(volatile uint32_t * )(GPIOA_Base + 0x04)
#define GPIOA_IDR            *(volatile uint32_t * )(GPIOA_Base + 0x08)


//GPIOB Registers B
#define GPIOB_CRL            *(volatile uint32_t *)(GPIOB_Base + 0x00)
#define GPIOB_CRH            *(volatile uint32_t * )(GPIOB_Base + 0x04)
#define GPIOB_ODR            *(volatile uint32_t *)(GPIOB_Base + 0x0C)


//RCC Registers
#define RCC_APB2ENR           *(volatile uint32_t *)(RCC_Base + 0x18)



void Clock_Init()
{

	/*Enable lock For GPIOA && GPIOB*/
	RCC_APB2ENR |=(0b11<<2);
}

void GPIO_Init()
{

	//Input Pins GPIOA Pin1 && Pin13
	//make GPIOA Pin 1 as Input Mode
	GPIOA_CRL &=~(0b01<<4);

	//make GPIOA Pin 1 as 01: Floating input (reset state)
	GPIOA_CRL |=(1<<6);
	GPIOA_CRL &=~(1<<7);


	//make GPIOA Pin 13 as Input Mode
	//make GPIOA Pin 13 as 01: Floating input (reset state)
	GPIOA_CRH &=~(0b11<<20);
	GPIOA_CRH |=(0b01<<22);




	//Output Pins GPIOB Pin1 && Pin13
	//make GPIOB Pin 1 as 10:Output Mode with max speed 2 MHz.
	GPIOB_CRL &=~(1<<4);
	GPIOB_CRL |= (1<<5);

	//make GPIOB Pin 1 General purpose output push-pull.
	GPIOB_CRL &=~(0b01<<6);

	//GPIOB Pin13
	//make GPIOB Pin 13 as 10:Output Mode with max speed 2 MHz.
	GPIOB_CRH &=~(1<<20);
	GPIOB_CRH |= (1<<21);

	//make GPIOB Pin 13 General purpose output push-pull.
	GPIOB_CRH &=~(0b11<<22);
}

void Wait()
{
	int i=0;
	for(i=0;i<2000;i++);
}




int main(void)
{
	Clock_Init();
	GPIO_Init();
	int flag=0;

	while(1)
	{

		//PA1 >>> is connected to PUR
		if(((GPIOA_IDR & (1<<1)) >>1 ) == 0 && flag==1) // button pressed == 1 bcs the button is BUR
			                                           //the right shift to compare with one or zero
		{
			GPIOB_ODR ^=(1<<1); // toggle led on PB1
			flag=0;

		}
		if(((GPIOA_IDR & (1<<1)) >>1 ) == 1)
		{
			flag=1;
		}


		//PA13 >>> is connected to PDR
		if(((GPIOA_IDR & (1<<13)) >>13 ) ==1 ) // button pressed
		{
			GPIOB_ODR ^=(1<<13); // toggle led on PB13 multipressing

		}

		Wait();
	}




}
