/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "STM32_F103C6.h"
#include "STM32F103C6_GPIO_DRIVERS.h"
#include "STM32F103C6_USART_DRIVERS.h"

unsigned char ch;

void Clock_Init()
{
	//Enable Clock
	RCC_GPIOA_CLOCK_EN();
	RCC_GPIOB_CLOCK_EN();
	RCC_AFIO_CLOCK_EN();
}

void Mostafa_CallBack(void)
{
	MCAL_UART_RECEIVE_DATA(USART1, &ch, disable);
        MCAL_UART_SEND_DATA(USART1, &ch, disable);

}

int main(void)
{

	USART_Config uartCFG;

	uartCFG.BaudRate = USART_BaudRate_115200;
	uartCFG.HW_FlowCtrl = USART_HW_FlowCtrl_NONE;
	uartCFG.IRQ_Enable = USART_IRQ_Enable_RXNE;
	uartCFG.P_IRQ_Call_Back = Mostafa_CallBack;
	uartCFG.Parity = USART_Parity_NONE;
	uartCFG.PayLoad_Length = USART_PayLoad_Length_8B;
	uartCFG.StopBits = USART_StopBits_1;
	uartCFG.USART_MODE = USART_MODE_RX_AND_TX;

	MCAL_UART_INIT(USART1, &uartCFG);

	MCAL_UART_GPIO_Set_Pins(USART1);



	while(1)
	{


	}

	return 0;

}












